definitions:
  model.CreateUserRequest:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
      roles:
        items:
          type: string
        type: array
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  model.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      is_active:
        type: boolean
      last_login_at:
        type: string
      metadata:
        additionalProperties:
          type: string
        type: object
      password:
        type: string
      permissions:
        items:
          type: string
        type: array
      roles:
        items:
          type: string
        type: array
      updated_at:
        type: string
      username:
        type: string
    type: object
  types.APIError:
    properties:
      code:
        type: string
      details:
        type: string
      message:
        type: string
    type: object
  types.APIResponse:
    properties:
      api_version:
        description: ApiVersion API 版本号
        type: string
      data:
        description: Data 响应数据,列表或单个对象
      error:
        allOf:
        - $ref: '#/definitions/types.APIError'
        description: Error 错误信息，当成功为 false 时必有
      pagination:
        allOf:
        - $ref: '#/definitions/types.Pagination'
        description: Pagination 分页信息
      success:
        description: Success 是否成功, true 表示成功, false 表示失败
        example: false
        type: boolean
      timestamp:
        description: 'Timestamp 响应时间戳, 单位: 毫秒'
        type: integer
    type: object
  types.Pagination:
    properties:
      limit:
        type: integer
      page:
        type: integer
      total:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/v1/register:
    post:
      consumes:
      - application/json
      description: 用户通过提供用户名和密码进行注册
      parameters:
      - description: 注册请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: 注册成功
          schema:
            allOf:
            - $ref: '#/definitions/types.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.User'
                error:
                  type: object
                success:
                  type: boolean
              type: object
        "400":
          description: 请求参数无效或注册失败
          schema:
            allOf:
            - $ref: '#/definitions/types.APIResponse'
            - properties:
                data:
                  type: object
                error:
                  $ref: '#/definitions/types.APIError'
                message:
                  type: string
                success:
                  type: boolean
              type: object
      summary: 用户注册
      tags:
      - 认证模块
swagger: "2.0"
